coreutils: Fix conflicts in multilib build
The new ptest dependencies present some challenges, in particular
libmodule-build-perl which effectively depends on gcc. In multilib
images, this results in both libXX-gcc-symlinks and libYY-gcc-symlinks
being installed which conflict.

Move libmodule-build-perl from RDEPENDS to RRECOMMENDS in order to get
rid of the following errors on image do_rootfs. If in RDEPENDS bitbake
will try to install libmodule-build-perl and if lib32-gcc have conflicts
with gcc it will exit with error. If in RRECOMENDS bitbake will not exit
with error if it's unable to install libmodule-build-perl and his gcc and
lib32-gcc dependencies.

Error: Transaction check error:
  file /usr/bin/gcc conflicts between attempted installs of gcc-symlinks-9.3.0-r0.core2_64 and lib32-gcc-symlinks-9.3.0-r0.core2_32
  file /usr/bin/cpp conflicts between attempted installs of cpp-symlinks-9.3.0-r0.core2_64 and lib32-cpp-symlinks-9.3.0-r0.core2_32
  file /usr/bin/g++ conflicts between attempted installs of lib32-g++-symlinks-9.3.0-r0.core2_32 and g++-symlinks-9.3.0-r0.core2_64

Related:
http://lists.openembedded.org/pipermail/openembedded-core/2020-March/294143.html

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>