linux-korg-netnext: Fix fetch failure for yocto-kernel-cache
Fix SRC_URI entries to be fetch: when frags are used, add
KERNEL_CONFIG_URI which point to yocto-kernel-cache and when
defconfig is used, do not clone this repo. The problem was the
fetch of this repo each time and when it used defconfig, the
repo is cloned in ${WORKDIR}, not in ${S} leaning to this error
when recompiling the kernel because the WORKDIR directory is
never empty even after a cleansstate.

ERROR: linux-korg-netnext-main.fa582ca7+git-r0 do_unpack: Bitbake Fetcher Error:
    git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all clone -n -s
    git2/git.yoctoproject.org.yocto-kernel-cache/ failed with exit code 12
    output:\nsh: 0: getcwd() failed: No such file or directory\nfatal: destination path
    '.../tmp/work/intel_axxia_pmr-intelaxxia-linux/linux-korg-netnext/main.fa582ca7+git'
    already exists and is not an empty directory.\n', None)

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>