eudev: Skip update_udev_hwdb postinst intercept
Because qemu usermode is not supported for axxiax86-64 BSP,
update_udev_hwdb postinst intercept will fail on do_rootfs
task for a read-only rootfs since it uses qemuwrapper:
NOTE: Exit code 1. Output:
      qemuwrapper: qemu usermode is not supported

It fails on old branches too but then it raised only warnings.
The build fails in dunfell starting with commit 32309ba1de62
("lib/oe/package_manager: turn postinst_intercept warnings
into failures for nativesdk") from poky.

Overwhite postinstal function to run only the "ontarget" code
and skip postinst_intercept call:
$INTERCEPT_DIR/postinst_intercept update_udev_hwdb ${PKG} \
       mlprefix=${MLPREFIX} binprefix=${MLPREFIX}

ERROR: axxia-image-vcn-1.0-r0 do_rootfs: The following packages could not
       be configured offline and rootfs is read-only: ['100-eudev-hwdb']

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>