rdk-tools: Disable parallel jobs for nura target
Nura target doesn't support random ordering of some operations,
thus force them to build single-threaded.

Otherwise, the build intermittently fails with the following
linker errors: undefined reference to:

gcc/x86_64-intelaxxia-linux/9.2.0/ld: sdk/ice/libice.a(nvm_ura_ice_common.o):
	in function `ice_cleanup_fltr_mgmt_single':
rdk/nvm_ura/sdk/ice/nvm_ura_ice_common.c:1223:
	undefined reference to `ice_rm_sw_replay_rule_info'
gcc/x86_64-intelaxxia-linux/9.2.0/ld: sdk/ice/libice.a(nvm_ura_ice_common.o):
	in function `ice_aq_get_rss_lut':
rdk/nvm_ura/sdk/ice/nvm_ura_ice_common.c:5376:
	undefined reference to `ice_is_vsi_valid'
...

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>