gdk-pixbuf: Skip update_pixbuf_cache postinst intercept
Because qemu usermode is not supported for axxiax86-64 BSP,
update_pixbuf_cache postinst intercept will fail on do_rootfs
task for a read-only rootfs since it uses qemuwrapper:
NOTE: Exit code 1. Output:
      qemuwrapper: qemu usermode is not supported

It fails on old branches too but it raised only warnings.
The build fails in dunfell starting with commit 32309ba1de62
("lib/oe/package_manager: turn postinst_intercept warnings
into failures for nativesdk") from poky.

Overwhite pixbufcache_common function from pixbufcache.bbclass
to run only the "ontarget" code and skip postinst_intercept call:
$INTERCEPT_DIR/postinst_intercept update_pixbuf_cache ${PKG} \
	mlprefix=${MLPREFIX} binprefix=${MLPREFIX} libdir=${libdir} \
	bindir=${bindir} base_libdir=${base_libdir}

ERROR: axxia-image-vcn-1.0-r0 do_rootfs: The following packages
       could not be configured offline and rootfs is read-only:
       ['101-libgdk-pixbuf-2.0-loader-jpeg',
       '102-libgdk-pixbuf-2.0-loader-gif',
       '104-libgdk-pixbuf-2.0-loader-xpm',
       '103-libgdk-pixbuf-2.0-loader-png']

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>