libvirt: Disable polkit feature
Remove polkit feature from PACKAGECONFIG in order to avoid the
following file conflict from do_rootfs step:

Error: Transaction check error:
file /usr/share/polkit-1/rules.d conflicts between attempted
	installs of libvirt-4.7.0-r0.core2snr_64 and
	polkit-0.115-r0.core2snr_64

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>