linux: Enable kvm support for all kernel versions
KVM kernel options are now enabled only for 4.19 kernel, but
kernel-module-kvm* sub-packages are included in axxia-image-vcn
unconditionally. If a different kernel version is built, KVM
options will not be enabled in kernel config, and there will be
no kvm modules built and no kernel-module-kvm sub-package created.
The build will fail on do_rootfs with:

ERROR: axxia-image-vcn-1.0-r0 do_rootfs: Could not invoke dnf.
No match for argument: kernel-module-kvm-amd
No match for argument: kernel-module-kvm
No match for argument: kernel-module-kvm-intel
Error: Unable to find a match

The right way to have KVM support is to add kvm distro feature
from meta-virtualization layer in our disto. This feature will
all the kernel options and some other settings for KVM.

In order to enable KVM support for all our kernel versions,
we'll require linux-yocto_virtualization.inc in linux-axxia.inc
because meta-virtualization enables KVM support only for official
supported kernel versions: linux-yocto 4.14 and 4.18.

And to get rid of all the warnings for duplicating inclusion of
linux-yocto_virtualization.inc, we'll skip parsing linux-yocto
bbappend recipes from meta-virtualization through BBMASK mechanism.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>