lttng-modules: upgrade to version 2.11.2
Upgrade to version 2.11.2 in order to fix build errors on kernel
greater than v5.4.19.

Starting with tag v5.4.19, kernel include the following commit
commit 8a1cd01bee ("KVM: x86: Use gpa_t for cr2/gpa to fix TDP
support on 32-bit KVM") which cause a build failure on
lttng-modules. This was fixed in the new version of lttng-modules
(v2.11.2) with the following commit commit 175c0c3c2e ("fix: KVM:
x86: Use gpa_t for cr2/gpa to fix TDP support on 32-bit (v5.6)").

Error messages:
tmp/work/axxiax86_64-intelaxxia-linux/lttng-modules/2.11.1-r0/lttng-modules-2.11.1/probes/../probes/lttng-tracepoint-event-impl.h:130:6:
error: conflicting types for 'trace_fast_page_fault'
  130 | void trace_##_name(_proto);
tmp/work-shared/axxiax86-64/kernel-source/include/linux/tracepoint.h:233:21:
note: previous definition of 'trace_fast_page_fault' was here
  233 |  static inline void trace_##name(proto)    \

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>