libxcrypt-compat: Fix packagedata conflicts with libxcrypt
Make libxcrypt-compat to provide only the main subpkg to avoid
conflicts with libxcrypt on do_packagedata:

ERROR: libxcrypt-compat-4.1.1-r0 do_packagedata: Recipe libxcrypt-compat
is trying to install files into a shared area when those files already
exist. The files and the manifests listing them are:
... tmp/pkgdata/intel-axxia-grr/runtime-reverse/libcrypt-dbg
(matched in manifest-intel_axxia_grr-libxcrypt.packagedata)
... tmp/pkgdata/intel-axxia-grr/runtime-reverse/libcrypt-dev
(matched in manifest-intel_axxia_grr-libxcrypt.packagedata)
Please adjust the recipes so only one recipe provides a given file.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>