iperf3: Upgrade to 3.20 version for GCC-15
| ../../git/src/iperf_api.c:608:28: error: assignment to 'void (*)(struct iperf_stream *)'
  from incompatible pointer type 'void (*)(void)' [-Wincompatible-pointer-types]
|   608 |         ipt->on_new_stream = callback;

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>