boost: Fix pyconfig.h header missing
Append CXXFLAGS variable to point to the python3 headers
instalation path in order to avoid the following error:

| ./boost/python/detail/wrap_python.hpp:57:11: fatal error:
|     pyconfig.h: No such file or directory
|  # include <pyconfig.h>
|            ^~~~~~~~~~~~

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>