db: Upgrade localy to version 6.2.23 which support Armv8
The version of Berkeley DB package from upstream is obsoleted for
ARMv8 and need to be updated from 6.0.30 to 6.2.23.
Till the upgrade will be done upstream, keep new recipes locally.
	ERROR: swp{b} use is obsoleted for ARMv8 and later

Also, do not build any native atomic operation support by disabling
atomicsupport option to avoid the folowing cross compiling error:
	configure: checking for atomic operations
	error: cannot run test program while cross compiling

Upstream-Status: Pending
Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>