simics-agent: Fix binaries not linked with LDFLAGS
Ensure LDFLAGS is passed to the linker to fix the error about
binaries which doesn't have GNU_HASH:

ERROR: simics-agent-6.0.163-r0 do_package_qa: QA Issue:
       File /usr/bin/simics-agent in package simics-agent
       doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

B0287 - GRR -- Update to Simics 6.0.163

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>