rdk-tools: Add lttng-ust andl ttng-tools as RDEPENDS
When RDK tools is built with LTTNG support, it require lttng-ust
and lttng-tools packages as run-time dependencies, not only
build-time dependencies.

Also, skip dev-deps QA check since rdk-tools automatically depends
(run-time) on the -dev package for lttng-ust:

ERROR: rdk-tools-1.0-grr_del4 do_package_qa: QA Issue: rdk-tools
       rdepends on lttng-ust-dev [dev-deps]
ERROR: rdk-tools-1.0-grr_del4 do_package_qa: QA run found fatal
       errors. Please consider fixing them.

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>