at: Solve mktime signature conflict for GCC-15 with C23 on
Remove mktime signature from posixtm.c. This is in conflict with
signature from system time.h.

extern time_t mktime (struct tm *__tp) __THROW;

GCC-15 with C23 on, this is treated at error

posixtm.c:45:8: error: conflicting types for 'mktime'; have 'time_t(void)' {aka 'long int(void)'}
|    45 | time_t mktime ();

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>