python3: Enable 'tk' feature in PACKAGECONFIG
Ensure Python is configured for Tk by enabling 'tk' feature in
PACKAGECONFIG for target and nativesdk classes.

>>> import tkinter
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/lib64/python3.10/tkinter/__init__.py", line 37, in <module>
   import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

B0272 - GRR/SNR -- tkinter change from Python 3.9 to Python 3.10

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>