perf: Update perf pmu-events sorting tool for newer kernels
When trying to build newer kernels (>5.16), perf fails because
the pmu-events sorting tool (sort-pmuevents-new.py) from hardknott
branch does not allow for additional type qualifiers and storage
class: AttributeError: 'NoneType' object has no attribute 'group'
This was fixed upstream in the following commit:

commit 44a3909bf61a29d279a5a0a23d62cb9b0fdd3b52
Author: Max Krummenacher <max.oss.09@gmail.com>
Date:   Mon Nov 22 17:34:59 2021 +0100
perf: sort-pmuevents: allow for additional type qualifiers and storage class
   With kernel 5.16 some structs in pmu-events do get a const qualifier, some
   a static const storage class and qualifier.
   The current sort-pmuevents cannot cope with that and drops all struct
   arrays with such additional elements. This then leads to compiler errors.
   Allow '^struct', '^const struct', '^static struct', '^static const struct'.

Overwrite sort-pmuevents.py script with the updated one. It works
fine with older versions of kernel too.