gcc-13: Use snapshots from gcc.gnu.org for sources
Proxies from Intel network blocks the git fetch from
repo.or.cz because it can't verify the certificate:

ERROR: cannot verify repo.or.cz's certificate, issued by
‘emailAddress=proxy.engineering@intel.com,CN=NSE sha2,OU=Network
Services Engineering,O=Proxy Engineering,ST=Oregon,C=US’:
  Self-signed certificate encountered.
To connect to repo.or.cz insecurely, use `--no-check-certificate'.

Instead using git sources, fetch snapshots from gcc.gnu.org.

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>