gstreamer: Disable vulkan support when python 3.6 is used
By enablink vulkan options in PACKAGECONFIG, gstreamer1.0-plugins-bad
package will depends on the native version of shaderc.

But shaderc package is quite new included in yocto and it doesn't
support an old version of python such as 3.6:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

As a workarround, disable vulkan support when compiling 'Bad' GStreamer
plugins with python 3.6.

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>