libxcrypt: Ignore warnings reported as errors by GCC 14 and newer
commit f7bf4fad01 ("lib/util-base64.c: Explicitly terminate the
c string") adds ane explicit terminator at the end of the base64
character array which is reported as error with GCC 14 and newer:

| ../git/lib/util-base64.c:24:3: error: initializer-string for array of
| 'unsigned char' is too long [-Werror=unterminated-string-initialization]
|    24 |   "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghipqrstuvwxyz"

Skip this as warning until will be fixed upstream.

A0403 - GRR/Scarthgap -- Build with Latest GCC

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>