axxia-image-large: Add libc-staticdev to SDK
In order to use -static flag to compile using SDK, we need to
specify in TOOLCHAIN_TARGET_TASK varible each staticdev subpkg
to have his static libraries in SDK.

Adding libc-staticdev to have static libc library in SDK.
ERROR: real-ld: cannot find -lc
collect2: error: ld returned 1 exit status

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>