linux-intel-rt: Upgrade to latest 4.19.72 tag
The default tag inherited from meta-intel layer for linux-intel-rt
fails to build with the following error. Upgrade to the latest tag
from linux-intel kernel repository to fix this.

arch/x86/events/intel/uncore_snbep.c:4544:15: error: 'uncore_freerunning_hw_config'
    undeclared here (not in a function); did you mean uncore_freerunning_counter'?
   .hw_config = uncore_freerunning_hw_config,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>