lsof: Upgrade to 4.99.6 version for GCC-15
| ../git/lib/misc.c:369:26: error: too many arguments to function 'r_fn'; expected 0, have 3
|   369 |                     rv = r_fn(r_arg, r.r_rbuf, r_rbln);

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>