linux: Alternative kernels should not provide virtual/kernel
Starting with commit f748564653 ("kernel: provide virtual/kernel
for all kernels") from poky, all kernels provide kernel virtual
target even if KERNEL_PACKAGE_NAME is not 'kernel', but other
alternative name. This was done to be sure each kernel should
be used as preferred provider for virtual/kernel.

The side efect is that we can't build multiple kernels in one build:
If you set PREFERRED_PROVIDER for a virtual/* item, then any recipe
that PROVIDES that item that is not selected by PREFERRED_PROVIDER
is prevented from building, which is usually desirable since this
mechanism is designed to select between mutually exclusive
alternative providers.

So, alternative kernels provides virtual/kernel alongside the main
kernel and will exclude each other:
ERROR: Nothing RPROVIDES 'altkernel-linux-intel-debug'
linux-intel-debug RPROVIDES altkernel-linux-intel-debug but was skipped:
PREFERRED_PROVIDER_virtual/kernel set to linux-intel, not linux-intel-debug

To fix this, ensure only the main kernel (KERNEL_PACKAGE_NAME=kernel)
provides virtual/kernel.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>