strongswan: Upgrade to 6.0.4 version for GCC-15
| ../../../strongswan-5.9.14/src/libstrongswan/processing/scheduler.c:332:87:
  error: passing argument 4 of 'callback_job_create_with_prio' from incompatible
  pointer type [-Wincompatible-pointer-types]
|   332 |               NULL, return_false, JOB_PRIO_CRITICAL);

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>