boost: Fix multilib do_package
MLPREFIX variable ('lib32-' value for multilib) is required
to specify multilib sub-packages where to install files
provided by compiling lib32 version of the package.
Otherwise, there will be files/directories installed but not
shipped in any package and do_package will fail.

ERROR: lib32-boost-1.70.0-r0 do_package: QA Issue: lib32-boost:
Files/directories were installed but not shipped in any package:
  /usr/lib/libboost_graph.so.1.70.0
  /usr/lib/libboost_iostreams.so.1.70
  /usr/lib/libboost_python39.so.1.70
  /usr/lib/libboost_atomic.so.1.70
  /usr/lib/libboost_program_options.so.1.70.0
  /usr/lib/libboost_math_tr1.so.1.70.0
  /usr/lib/libboost_regex.so.1.70.0
  /usr/lib/libboost_wave.so.1.70
  /usr/lib/libboost_wserialization.so.1
  /usr/lib/libboost_chrono.so.1.70
  /usr/lib/libboost_timer.so.1
  /usr/lib/libboost_container.so.1.70
  /usr/lib/libboost_python39.so.1.70.0
  /usr/lib/libboost_regex.so.1.70
  /usr/lib/libboost_log_setup.so.1.70
  ...

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>