thrift: Remove old 0.11.0 version
This specific version of thrift was required by RDK drivers/tools
on RPC (remote procedure call) mode. We'll try to use the default
version from upstream (0.16.0).

Also, remove staticdev sub-package from axxia-image-dev since the
upstream version does not provide it:
Error: Unable to find a match: thrift-staticdev

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>