libxt: Upgrade recipe to 1.3.1 required by GCC-15
| ../../libXt-1.3.0/src/Shell.c:1005:20: error: expected identifier or '(' before 'true'
|  1005 |     static Boolean true = True;
| ../../libXt-1.3.0/src/Shell.c:1008:35: error: lvalue required as unary '&' operand
|  1008 |         value->addr = (XPointer) (&true);

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>