bats: fix multilib file install conflicts
Use multilib_script class to avoid issues like this on a multilib build:

Error: Transaction test error:
  file /usr/libexec/bats-core/bats conflicts between attempted installs
       of bats-1.6.1-r0.grr_64 and lib32-bats-1.6.1-r0.grr_32
  file /usr/libexec/bats-core/bats-exec-file conflicts between attempted
       installs of bats-1.6.1-r0.grr_64 and lib32-bats-1.6.1-r0.grr_32
  file /usr/libexec/bats-core/bats-exec-test conflicts between attempted
       installs of bats-1.6.1-r0.grr_64 and lib32-bats-1.6.1-r0.grr_32

This will be removed when fixed upstream.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>