vala: fix multilib file install conflicts
Use multilib_script class to avoid issues like this on a multilib build:

Error: Transaction test error:
  file /usr/bin/vala-gen-introspect-0.56 conflicts between attempted
       installs of vala-0.56.3-r0.grr_64 and lib32-vala-0.56.3-r0.grr_32
  file /usr/bin/vapigen-wrapper conflicts between attempted installs
       of vala-0.56.3-r0.grr_64 and lib32-vala-0.56.3-r0.grr_32

This will be removed when fixed upstream.

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>