python3: autoreconf in-tree libffi for 3.6 version
The _ctypes python3 modules is compiled from python3 sources
and it requires libffi. There is a compatible version of libffi
in python3 sources (Modules/_ctypes/libffi) but the libffi
package installed on the system can be used if --with-system-ffi
configure flag is used (this is how the Yocto recipe from upstream
works starting with 3.5.6 version).

For the hardknott default version of python3 (3.9.5) the libffi
from the sysroot is compatible (v3.3) and the _ctypes module
is compiled. But for the 3.6.12 version, the configure configure
for _ctypes modules fails because of incompatible libffi:

warning: building with the bundled copy of libffi is deprecated
on this platform.  It will not be distributed with Python 3.7
env: tmp/work/snr-64-intelaxxia-linux/python3/3.6.12-r0/Python-3.6.12/\
     Modules/_ctypes/libffi/configure: No such file or directory
Failed to configure _ctypes module

The build doesn't fail, but on target the _ctypes module is not found:

root@intel-axxia-snr:~# python
Python 3.6.12 (default, Aug 15 2020, 06:59:32)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '_ctypes'

To fix this, we need to run autoreconf in Modules/_ctypes/libffi in
order to use the in-tree version of libffi for python3.6.

A0344 - GRR/SNR -- Add Python3 Ctypes

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>