rdk-tools: Add explicit dependencies
Starting with commit 04b37f914e ("layer.conf: Extend recipes
not to install without explict dependencies") from poky, the
list of dependencies which are not needed at runtime, but only
at build time (SSTATE_EXCLUDEDEPS_SYSROOT) was extended and
includes now also ninja-native and pkgconfig-native. This was
done to speeds up and reduces the sstate needed for image builds.

That's why we need to explicitly add in DEPENDS ninja-native
and pkgconfig-native which are required at build time:
ERROR: Could not detect Ninja v1.8.2 or newer
ERROR: Pkg-config binary for machine 1 not found. Giving up.

Also, the License was fixed since GPLv2 is obsoleted:
WARNING: rdk-tools-1.0-grr_del12 do_package_qa: QA Issue:
Recipe LICENSE includes obsolete licenses GPLv2 [obsolete-license]

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>