gcc-sanitizers: Fix 8.3 build with newer glibc
Backport patch to fix the gcc-sanitizers build with the new glibc
version (2.31 - default on dunfell branch) that breaks arm bootstrap
due to libsanitizer.

In file included from work-shared/gcc-8.3.0-r0/gcc-8.3.0/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:193:
work-shared/gcc-8.3.0-r0/gcc-8.3.0/libsanitizer/sanitizer_common/sanitizer_internal_defs.h:317:72: error:
size of array 'assertion_failed__1152' is negative
     typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>