simicsfs-client: Add fuse3 dependency
The new Simics (7.81.0) depends on fuse3 instead of fuse.
Keep both dependencies for backward compatibility since
there are no conflicts between them.

| simicsfs-prot.h:23:10: fatal error: fuse3/fuse.h: No such file or directory
|    23 | #include <fuse3/fuse.h>
|       |          ^~~~~~~~~~~~~~
| compilation terminated.
| make: *** [Makefile:47: simicsfs-client.o] Error 1

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>