linux: Append SRC_URI for axxiax86-64 machine
Otherwise yocto-check-layer scrips fails on test_signatures:

INFO: FAIL: test_signatures (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
AssertionError: Adding layer meta-intel-snr changed signatures.
  136 signatures changed, initial differences (first hash before, second after):
    linux-yocto:do_fetch: b345b49a7a05ff7fd4f6812f7bd9e422 -> 4ef8e611b15f51da60ec5576a2c6bbc7
    bitbake-diffsigs --task linux-yocto do_fetch --signature b345b49a7a05ff7fd4f6812f7bd9e422 4ef8e611b15f51da60ec5576a2c6bbc7
    NOTE: Starting bitbake server...
    basehash changed from a44f7a17e36c0c29ccfb89bacb9456b0 to 8c980c9dc1ceac2f81f10990b1252e20
    Variable PV value changed from '4.12.19+gitAUTOINC+44a22d45cb_257f843ea3' to '4.12.19+gitAUTOINC+7986844d9d_257f843ea3'

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>