rdk-tools: Fix compile intermittent errors
Ensure ies_api_install build is complete, then invoke cli target.
Otherwise, on the same oe_runmake call, there were intermittent
build failure caused by random ordering of operations:

rdkVersion.c:34:10: fatal error: ies_addr.h: No such file or directory
   34 | #include "ies_addr.h"

Also nura target doesn't support random ordering of some operations,
thus force it to build single-threaded:

rdk/nvm_ura/sdk/ice/nvm_ura_ice_sched.c:2651: undefined reference to `ice_is_vsi_valid'
ld: sdk/ice/libice.a(nvm_ura_ice_sched.o): in function `ice_sched_replay_vsi_bw':
rdk/nvm_ura/sdk/ice/nvm_ura_ice_sched.c:3972: undefined reference to `ice_get_vsi_ctx'
collect2: error: ld returned 1 exit status

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: Sudhir Gopal <sudhir.gopal@intel.com>