bpftool: Fix missing header from STAGING_INCDIR
elfutils-native provides libelf.h header, but the CC compiler doesn't
find it in STAGING_INCDIR in the native build.

| In file included from ringbuf.c:22:
| libbpf_internal.h:20:10: fatal error: libelf.h: No such file or directory
|    20 | #include <libelf.h>

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>