postfix: Fix build failures with glibc 2.30
Backport patch from meta-openembedded layer, master branch,
revision ca22e1996da. This fixes build failures with glibc 2.30
due to dropped RES_INSECURE1/2 macros:

dns_str_resflags.c:63:22: error: ‘RES_INSECURE1’ undeclared here (not in a function); did you mean ‘RES_RECURSE’?
     "RES_INSECURE1", RES_INSECURE1,
dns_str_resflags.c:64:22: error: ‘RES_INSECURE2’ undeclared here (not in a function); did you mean ‘RES_RECURSE’?
     "RES_INSECURE2", RES_INSECURE2,
dns_str_resflags.c:66:22: error: ‘RES_USE_INET6’ undeclared here (not in a function)
     "RES_USE_INET6", RES_USE_INET6,

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>