kernel-devsrc: Install additional headers for latest RDK code
Additional headers from arch/x86/kvm/mmu are required to
be installed in kernel-devsrc for lates RDK lttng code:

drivers/lttng-modules/src/probes/lttng-probe-kvm-x86-mmu.c:28:10:
   fatal error: ../../arch/x86/kvm/mmu/mmu_internal.h: No such file or directory
   28 | #include <../../arch/x86/kvm/mmu/mmu_internal.h>

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>