DEPENDENCIES: Fix not deterministic metadata for Poky
We can avoid reparsing the same recipe by including Poky
commit cfd897e213d, which prevents the following issue
from occurring when building the SDK first time:

ERROR: When reparsing ..poky/meta/recipes-core/meta/meta-environment.bb:do_generate_content,
       the basehash value changed from <SHA> to <SHA>.
       The metadata is not deterministic and this needs to be fixed.

commit 076d50da2e5652088d453d12eba0b5b445f29f85
metadata_scm.bbclass: Use immediate expansion for the METADATA_* variables"
       Define METADATA_BRANCH and METADATA_REVISION using immediate expansion.
       This avoids running `git rev-parse HEAD` multiple times during recipe
       parsing.

As a consequence, the revision for meta-intel was also updated.

B0258 - SNR -- Build Errors... But Build Completes!?!?

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>