linux-intel: Complete the iTCO_wdt Ignore Reboot Bit Patch
This work-around need to be implemented also in start and
stop methods for the iTCO_wdt driver where it tries to access
the NO_REBOOT bit.
Otherwise, this call trace will be displayed on boot time:

iTCO_wdt: Intel TCO WatchDog Timer Driver v1.11
iTCO_wdt: Found a Intel PCH TCO device (Version=4, TCOBASE=0x0400)
BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
PGD 2733ea067 P4D 2733ea067 PUD 2733eb067 PMD 0
Oops: 0000 [#1] PREEMPT SMP NOPTI
CPU: 1 PID: 276 Comm: udevd Not tainted 4.19.40-intel-axxia-standard snr_version-test
Hardware name: Intel Corporation JACOBSVILLE/JACOBSVILLE, BIOS JBVLCRB1.86B.0008.D51.1902201706 02/20/2019
RIP: 0010:update_no_reboot_bit_mem+0x10/0x90 [iTCO_wdt]
Code: Bad RIP value.
RSP: 0018:ffffc900018f3a88 EFLAGS: 00010206
RAX: 0000000000000000 RBX: 0000000074001800 RCX: 0000000000000000
RDX: 0000000000000408 RSI: 0000000000000001 RDI: ffff8882756ac618
RBP: ffffc900018f3a88 R08: 000000000000046f R09: 0000000000000007
R10: 0000000000000000 R11: 0000000000000000 R12: ffff8882756ac618
R13: ffff8882756ac6e8 R14: ffff8882740ad410 R15: 0000000000000005
FS:  00007fcf15b802c0(0000) GS:ffff888277c40000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: ffffffff9ffffff6 CR3: 000000027141a000 CR4: 0000000000340ee0
Call Trace:
 iTCO_wdt_stop+0x58/0x80 [iTCO_wdt]
 iTCO_wdt_probe.cold.10+0xc2/0x1ab [iTCO_wdt]
 platform_drv_probe+0x3d/0x90
 really_probe+0x244/0x3c0
 driver_probe_device+0x61/0x110
 __driver_attach+0xf3/0x110
 ? driver_probe_device+0x110/0x110
 ? driver_probe_device+0x110/0x110
 bus_for_each_dev+0x74/0xb0
 ? _raw_spin_unlock+0x16/0x30
 driver_attach+0x1e/0x20
 bus_add_driver+0x1dd/0x240
 ? 0xffffffffa0005000
 driver_register+0x70/0xc0
 ? 0xffffffffa0005000
 __platform_driver_register+0x36/0x40
 iTCO_wdt_init_module+0x2f/0x1000 [iTCO_wdt]
 do_one_initcall+0x53/0x1fe
 ? __vunmap+0x8e/0xc0
 ? kmem_cache_alloc_trace+0x33/0x1d0
 ? kfree+0x18e/0x1b0
 do_init_module+0x60/0x210
 load_module+0x1f41/0x21d0
 ? vfs_read+0xf4/0x120
 ? vfs_read+0xf4/0x120
 __do_sys_finit_module+0xe2/0x120
 ? __do_sys_finit_module+0xe2/0x120
 __x64_sys_finit_module+0x1a/0x20
 do_syscall_64+0x86/0x170
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x3e2b8ef519
Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 8
RSP: 002b:00007fff4f0b5688 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
RAX: ffffffffffffffda RBX: 00000000016f7d70 RCX: 0000003e2b8ef519
RDX: 0000000000000000 RSI: 00000000016dcf80 RDI: 0000000000000008
RBP: 0000000000000000 R08: 0000000000000000 R09: 00000000016f7d70
R10: 0000000000000008 R11: 0000000000000246 R12: 00000000016dcf80
R13: 0000000000020000 R14: 0000000000000000 R15: 0000000000000000
Modules linked in: iTCO_wdt(+)
CR2: 0000000000000000
---[ end trace 9324aa2f9e7cdb0e ]---
RIP: 0010:update_no_reboot_bit_mem+0x10/0x90 [iTCO_wdt]
Code: Bad RIP value.

Be aware that to enable the work-around you need to add
'iTCO_wdt.assume_noreboot_access=1' to the Linux command line.

Also, fix the fallowing checkpatch error for the patch:
ERROR: do not initialise statics to 0
+static int assume_noreboot_access = 0;

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>