axxia-image-dev: Add 32-bit libxcrypt-compat for multilib
In a multilib build, add 32-bit version of libxcrypt-compat
package to have in rootfs 32-bit version of libcrypt.so.1
library which contains obsolete APIs, needed for uninative
in particular.

Add -dev sub-package in PACKAGE_EXCLUDE for axxia-image-dev to
avoid conflicts with lib32-libxcrypt package (which provides
libcrypt.so.2) for /usr/lib/libcrypt.so symlink:

Error: Transaction test error:
    file /usr/lib/libcrypt.so from install of
    lib32-libxcrypt-compat-dev-4.4.18-r0.grr_32 conflicts with
    file from package lib32-libcrypt-dev-4.4.18-r0.grr_32

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>