lttng-modules: Fix build with 4.19.152 kernel
Backport one patch from v2.11.2 and 3 from v2.11.6 tags to fix
compile errors when compiling with 4.19.152 kernel (see commit
log for each for the fix details):
- fix: KVM: x86: Use gpa_t for cr2/gpa to fix TDP support on 32-bit (v5.6)
- fix: ext4: limit the length of per-inode prealloc list (v5.9)
- fix: writeback: Fix sync livelock due to b_dirty_time processing (v5.9)
- fix: version ranges for ext4_discard_preallocations and writeback_queue_io

This backport is fixing the following compile errors:

In file included from lttng-modules/2.10.9-r0/lttng-modules-2.10.9/probes/../probes/define_trace.h:100,
|                from ttng-modules/2.10.9-r0/lttng-modules-2.10.9/probes/../instrumentation/events/lttng-module/arch/x86/kvm/mmutrace.h:235,
|                from ttng-modules/2.10.9-r0/lttng-modules-2.10.9/probes/lttng-probe-kvm-x86-mmu.c:52:
| lttng-modules/2.10.9-r0/lttng-modules-2.10.9/probes/../probes/lttng-tracepoint-event-impl.h:143:6:
                 error: conflicting types for 'trace_fast_page_fault'
|   143 | void trace_##_name(_proto);
        |      ^~~~~~

In file included from lttng-modules-linux-intel-rt/2.11.5-r0/lttng-modules-2.11.5/probes/../probes/define_trace.h:87,
|                from lttng-modules-linux-intel-rt/2.11.5-r0/lttng-modules-2.11.5/probes/../instrumentation/events/lttng-module/writeback.h:786,
|                from lttng-modules-linux-intel-rt/2.11.5-r0/lttng-modules-2.11.5/probes/lttng-probe-writeback.c:38:
| lttng-modules-linux-intel-rt/2.11.5-r0/lttng-modules-2.11.5/probes/../probes/lttng-tracepoint-event-impl.h:130:6:
                 error: conflicting types for 'trace_writeback_queue_io'
|   130 | void trace_##_name(_proto);
|      ^~~~~~

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>