distro: Overwrite SAVANNAH_NONGNU_MIRROR for Intel proxy
By default, SAVANNAH_NONGNU_MIRROR variable points to
https://download.savannah.nongnu.org/releases which on
Intel network (proxy protected) fails to fetch sources
because it cannot check the certificate:
ERROR: cannot verify download.savannah.nongnu.org's certificate

It switch to mirrors and the one choosen by Intel proxy
server has broken archives, with different sha356sum:
ERROR: freetype-2.11.1-r0 do_fetch: Bitbake Fetcher Error:
ChecksumError('Checksum mismatch!\nFile: ..freetype-2.11.1.tar.xz
has sha256 checksum \'ed2530cbbcc..\' when \'3333ae7cfda8..\'
was expected.

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>