linux-local: Skip missing fragments errors
Since linux-local uses full defconfig files, we don't fetch
meta-data repository (yocto-kernel-cache) which contains
kernel fragments. In scarthgap branch KERNEL_FEATURES variable
defined in linux-yocto.inc file from poky contains multiple
.scc fragments depending on what MACHINE_FEATURES are active.
Since KERNEL_FEATURES can't be overwritten from other bbappend
recipes, the only solution is to turn those errors in warnings
using KERNEL_DANGLING_FEATURES_WARN_ONLY variable [1].

ERROR: linux-local-dev-version-r0 do_kernel_metadata: Feature
'cfg/efi.scc' not found, this will cause configuration failures.

[1] https://docs.yoctoproject.org/ref-manual/variables.html#\
    term-KERNEL_DANGLING_FEATURES_WARN_ONLY

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>