bats: fix multilib file install conflicts
Use multilib_script class to avoid other issues like
this on a multilib build:

Error: Transaction test error:
file /usr/libexec/bats-core/bats-exec-suite conflicts
  between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32
file /usr/libexec/bats-core/bats-format-junit conflicts
  between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32
file /usr/libexec/bats-core/bats-format-pretty conflicts
   between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32
file /usr/libexec/bats-core/bats-format-tap conflicts
   between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32
file /usr/libexec/bats-core/bats-format-tap13 conflicts
   between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32
file /usr/libexec/bats-core/bats-preprocess conflicts
   between attempted installs of bats-1.10.0-r0.grr_64 and lib32-bats-1.10.0-r0.grr_32

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>