babeltrace: Fix installed-vs-shipped error for multilib
When enabling python-bindings for babeltrace, the install path
for the python modules is the same for a normal build and also for
a multilib one: /usr/lib.
Since libdir variable is different for a multilib build
(/usr/lib64), we should use nonarch_libdir one in order to have
files installed in python3-babeltrace sub-package.

ERROR: babeltrace-1.5.8-r0 do_package: QA Issue: babeltrace:
        Files/directories were installed but not shipped in any package:
/usr/lib/python3.6/site-packages/babeltrace-1.5.8-py3.6.egg-info
/usr/lib/python3.6/site-packages/babeltrace/_babeltrace.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3.6/site-packages/babeltrace/babeltrace.py
/usr/lib/python3.6/site-packages/babeltrace/__init__.py
Please set FILES such that these items are packaged. Alternatively if
they are unneeded, avoid installing them or delete them within do_install.
babeltrace: 4 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>